name: Schedule Friday 0700

on:
  schedule:
    - cron:  '0 7 * * 5'

jobs:
  Add-Update-Label-to-Issues-Weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        env:
          IN_PROGRESS_COLUMN_ID: ${{ secrets.TEST_COLUMN_ID }}
        with:
          script: |
            const { TEST_COLUMN_ID } = process.env;
            const script = require('./github-actions/trigger-schedule/add-update-label-weekly/add-label.js');
            script({ g: github, c: context }, TEST_COLUMN_ID);
